### ISSUE TITLE
GitLab ocaml-ci not parsing ref

### ISSUE THREAD

**Issue by tmcgilchrist** [tarides/tezos-ci#24]
The code for parsing GitLab git refs make certain assumptions about the structure of the ref based off GitHub.

See https://gitlab.tezos.ci.dev/gitlab/tmcgilchrist/ocaml-gitlab/commit/db3406845fe867ed0a86a3b5cf4195420a863099

**Comment by novemberkilo** [comment]
Fixed via https://github.com/tmcgilchrist/ocaml-ci/pull/1
